storage.file=player-economy-storage.properties

currency.keys=gold,rare_crystal
currency.gold.displayName=Gold
currency.gold.defaultBalance=0
currency.rare_crystal.displayName=Rare Crystal
currency.rare_crystal.defaultBalance=0
